# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=10)),
                ('bill_number', models.CharField(max_length=10)),
                ('bill_name', models.CharField(max_length=100)),
                ('introduction_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=100)),
                ('journal_page', models.CharField(max_length=50)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Introducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducer_id', models.CharField(max_length=10)),
                ('introducer_name', models.CharField(max_length=50)),
                ('introduced_bills', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TextCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='introducer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Introducer'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill'),
        ),
    ]
