# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_introducer_introduced_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='introducer',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='introducer',
            name='introducer_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
