# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20161121_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('legislature_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('legislature', models.CharField(max_length=5)),
                ('session', models.CharField(max_length=1)),
            ],
        ),
    ]
