# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_legislature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='introducer_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='introducer_id',
            field=models.ManyToManyField(to='bills.Introducer'),
        ),
    ]
